name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        shell: cmd
        run: |
          call "%ProgramFiles%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath > vs_path.txt
          set /p VS_PATH=<vs_path.txt
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          cl /std:c++17 /O2 main.cpp /Fe:MyLoader.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: MyLoader
          path: MyLoader.exe
